# Record the source actually configured and reject incompatible installed SDKs.
openms4_source_revision(PYOPENMS_SOURCE_REVISION PYOPENMS_SOURCE_DIRTY)
if(NOT EXISTS "${OpenMS_BUILD_INFO_FILE}")
  message(FATAL_ERROR "The pinned SDK must provide OpenMS_BUILD_INFO_FILE with runtime build identity")
endif()
file(READ "${OpenMS_BUILD_INFO_FILE}" _core_build_info)
foreach(_field schema_version source_revision build_type system_name system_processor cxx_standard shared_libs)
  string(JSON _core_${_field} GET "${_core_build_info}" ${_field})
endforeach()
if(NOT _core_schema_version EQUAL 1 OR NOT _core_source_revision STREQUAL OpenMS_SOURCE_REVISION)
  message(FATAL_ERROR "OpenMS build identity does not match the pinned SDK configuration")
endif()
if(NOT _core_system_name STREQUAL CMAKE_SYSTEM_NAME)
  message(FATAL_ERROR "OpenMS SDK platform mismatch: ${_core_system_name} versus ${CMAKE_SYSTEM_NAME}")
endif()
set(_python_arch "${CMAKE_SYSTEM_PROCESSOR}")
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
  set(_python_arch "${CMAKE_OSX_ARCHITECTURES}")
endif()
string(TOLOWER "${_python_arch}" _python_arch)
string(TOLOWER "${_core_system_processor}" _core_arch)
foreach(_arch _python_arch _core_arch)
  if(${_arch} STREQUAL "aarch64")
    set(${_arch} arm64)
  elseif(${_arch} STREQUAL "amd64")
    set(${_arch} x86_64)
  endif()
endforeach()
if(NOT _python_arch STREQUAL _core_arch)
  message(FATAL_ERROR "OpenMS SDK architecture mismatch: ${_core_arch} versus ${_python_arch}")
endif()
get_property(_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(_multi_config)
  # A single-config SDK cannot supply another configuration's runtime ABI.
  set(CMAKE_CONFIGURATION_TYPES "${_core_build_type}" CACHE STRING "Configurations supplied by the pinned SDK" FORCE)
elseif(NOT CMAKE_BUILD_TYPE STREQUAL _core_build_type)
  message(FATAL_ERROR "OpenMS SDK build configuration mismatch: ${_core_build_type} versus ${CMAKE_BUILD_TYPE}; select a matching SDK or CMAKE_BUILD_TYPE")
endif()
if(NOT _core_cxx_standard EQUAL CMAKE_CXX_STANDARD OR NOT _core_shared_libs)
  message(FATAL_ERROR "pyOpenMS requires a shared OpenMS SDK with matching C++ standard")
endif()
string(JSON _core_openswath GET "${_core_build_info}" features openswath)
if(NOT _core_openswath)
  message(FATAL_ERROR "pyOpenMS requires the OpenSWATH SDK feature")
endif()
set(_python_source_dirty false)
if(PYOPENMS_SOURCE_DIRTY)
  set(_python_source_dirty true)
endif()
set(_pyopenms_provenance "{\"schema_version\":1,\"source_revision\":\"${PYOPENMS_SOURCE_REVISION}\",\"source_dirty\":${_python_source_dirty},\"version\":\"${PYOPENMS_PACKAGE_VERSION}\",\"core\":${_core_build_info}}")
string(JSON _core_standard_library GET "${_core_build_info}" standard_library)
string(JSON _core_libstdcxx_cxx11_abi GET "${_core_build_info}" libstdcxx_cxx11_abi)
string(JSON _core_msvc_runtime_library GET "${_core_build_info}" msvc_runtime_library)
set(PYOPENMS_EXPECT_LIBCXX 0)
set(PYOPENMS_EXPECT_LIBSTDCXX 0)
set(PYOPENMS_EXPECT_MSVC 0)
if(_core_standard_library STREQUAL "libc++")
  set(PYOPENMS_EXPECT_LIBCXX 1)
elseif(_core_standard_library STREQUAL "libstdc++")
  set(PYOPENMS_EXPECT_LIBSTDCXX 1)
elseif(_core_standard_library STREQUAL "msvc-stl")
  set(PYOPENMS_EXPECT_MSVC 1)
else()
  message(FATAL_ERROR "Unsupported OpenMS SDK C++ standard library: ${_core_standard_library}")
endif()
if(MSVC)
  # Match the actual SDK CRT selection; CMake applies this to each binding module.
  set(CMAKE_MSVC_RUNTIME_LIBRARY "${_core_msvc_runtime_library}")
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/runtime_abi.h.in"
  "${CMAKE_CURRENT_BINARY_DIR}/generated/runtime_abi.h" @ONLY)
